// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmjmuafaamdozxwsrvrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtam11YWZhYW1kb3p4d3NydnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NjIyNTUsImV4cCI6MjA1NTQzODI1NX0.O73_7AIQUYVe_orIrs3gLjzZ-vuu9AeyiCNh1TTRRyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);